import type { Metadata } from 'next';
import { ThemeProvider } from '~/components/contexts/theme-provider';
import { Geist, Geist_Mono } from 'next/font/google';
import '~/styles/globals.css';

export const metadata: Metadata = {
  title: 'Untitled Design_',
  description: 'Generated by create next app',
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export async function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'es' }];
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          storageKey="theme"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
